//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductionWorker.h
//  @ Date : 3/14/2017
//  @ Author : Austin Acosta
//
//


#if !defined(_PRODUCTIONWORKER_H)
#define _PRODUCTIONWORKER_H

#include "Employee.h"

class ProductionWorker : public Employee {
public:
	ProductionWorker(string newName, int newNumber, char newLetter, int newShift, double newHourlyPayRate);
	int getShift();
	double getHourlyPayRate();
	void setShift(int newShift);
	void setHourlyPayRate(double newHourlyPayRate);
private:
	int shift;
	double hourlyPayRate;
};

#endif  //_PRODUCTIONWORKER_H
