//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ProductionWorker.cpp
//  @ Date : 3/14/2017
//  @ Author : Austin Acosta
//
//


#include "ProductionWorker.h"
#include <iostream>

using namespace std;

//TODO Write the constructor ProductionWorker(string newName, int newNumber, char newLetter, int newShift, double newHourlyPayRate)
ProductionWorker::ProductionWorker(string newName, int newNumber, char newLetter, int newShift, double newHourlyPayRate) : Employee(newName, newNumber, newLetter){
    shift = newShift;
    hourlyPayRate = newHourlyPayRate;
}


int ProductionWorker::getShift() {
    return shift;
}

double ProductionWorker::getHourlyPayRate() {
   // TODO return the member variable
   return hourlyPayRate;
}

void ProductionWorker::setShift(int newShift) {
    shift = newShift;
}

void ProductionWorker::setHourlyPayRate(double newHourlyPayRate) {
    // TODO Change the corresponding member variable
    hourlyPayRate = newHourlyPayRate;
}

int main(){
    ProductionWorker *peter = new ProductionWorker("Peter", 12345, 'P', 1, 35.89);
    cout << "Name: " << peter->getName() << endl
         << "ID: " << peter->getID() << endl
	 << "Hourly pay rate: " << peter->getHourlyPayRate() << endl;

    return 0;
}
